apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-backend
  template:
    metadata:
      labels:
        app: video-backend
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/video-backend:latest
        ports:
        - containerPort: 5000
